"""rename address

Revision ID: 22413e38377a
Revises: d5aab4c52490
Create Date: 2024-04-04 19:01:24.431567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22413e38377a'
down_revision = 'd5aab4c52490'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('location', sa.String(), nullable=True))
    op.drop_column('departments', 'address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('address', sa.VARCHAR(), nullable=True))
    op.drop_column('departments', 'location')
    # ### end Alembic commands ###
